services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ci-django-container
    environment:
      DB_HOST: database # Changed format
      DB_NAME: pet_store
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      - database
    networks:
      - app-network # Add this
    volumes:
      - ./backend:/app
      - ./backend/requirements.txt:/app/requirements.txt

  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: ci-db-container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - app-network # Add this
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres:/var/lib/postgresql/data

networks: # Add this section
  app-network:
    driver: bridge

volumes:
  postgres:
