name: Rut tests - Backend

on:
  push:
    branches: ["main", "dev"]
    paths:
      - "backend/**"
      - "database/init.sql"
  pull_request:
    branches: ["main", "dev"]
    paths:
      - "backend/**"
      - "database/init.sql"

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: docker compose run --rm backend sh -c "python manage.py test"
