name: Rut tests - Backend

on:
  [push]
  # push:
  #   branches: ["main", "dev"]
  #   paths:
  #     - "backend/**"
  #     - "database/init.sql"
  # pull_request:
  #   branches: ["main", "dev"]
  #   paths:
  #     - "backend/**"
  #     - "database/init.sql"

jobs:
  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Database environment variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_ENV

      - name: Run Backend Tests
        run: docker compose -f docker-compose.yml run --rm backend sh -c "python manage.py wait_for_db && python manage.py test"
